export const DESTINATIONS = [
  {
    id: 'dest-1',
    name: 'Jaipur',
    state: 'Rajasthan',
    tagline: 'The Pink City of Palaces',
    description: 'Explore majestic forts, royal palaces, vibrant bazaars, and rich Rajputana heritage.',
    image: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1000&q=80',
    hotelCount: 340,
    startingPrice: '₹ 2,499',
    rating: 4.9,
    popular: true,
  },
  {
    id: 'dest-2',
    name: 'Udaipur',
    state: 'Rajasthan',
    tagline: 'City of Lakes & Romance',
    description: 'Serene lakefront luxury, royalhavelis, and breathtaking sunset boat cruises.',
    image: 'https://images.unsplash.com/photo-1615880484746-a134be9a6ecf?auto=format&fit=crop&w=1000&q=80',
    hotelCount: 210,
    startingPrice: '₹ 3,199',
    rating: 4.9,
    popular: true,
  },
  {
    id: 'dest-3',
    name: 'Goa',
    state: 'Goa',
    tagline: 'Sun, Sand & Beach Resorts',
    description: 'Pristine beaches, luxury beachfront villas, nightlife, and Portuguese heritage.',
    image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1000&q=80',
    hotelCount: 520,
    startingPrice: '₹ 2,999',
    rating: 4.8,
    popular: true,
  },
  {
    id: 'dest-4',
    name: 'Mumbai',
    state: 'Maharashtra',
    tagline: 'The City of Dreams & Sea Views',
    description: 'Iconic harbor vistas, five-star heritage hotels, and world-class culinary experiences.',
    image: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=1000&q=80',
    hotelCount: 480,
    startingPrice: '₹ 4,500',
    rating: 4.7,
    popular: true,
  },
  {
    id: 'dest-5',
    name: 'Jodhpur',
    state: 'Rajasthan',
    tagline: 'The Sun City & Blue Forts',
    description: 'Imposing Mehrangarh Fort view stays, desert safari luxury tents, and traditional hospitality.',
    image: 'https://images.unsplash.com/photo-1589308078059-be1415eab4c3?auto=format&fit=crop&w=1000&q=80',
    hotelCount: 180,
    startingPrice: '₹ 2,799',
    rating: 4.8,
    popular: false,
  },
  {
    id: 'dest-6',
    name: 'Delhi NCR',
    state: 'Delhi',
    tagline: 'Capital Luxury & Modern Comforts',
    description: 'Ultra-modern boutique hotels, historical monuments, and luxury business suites.',
    image: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=1000&q=80',
    hotelCount: 650,
    startingPrice: '₹ 3,499',
    rating: 4.7,
    popular: false,
  },
  {
    id: 'dest-7',
    name: 'Kerala',
    state: 'Kerala',
    tagline: 'God\'s Own Country',
    description: 'Tranquil backwater houseboats, Ayurvedic wellness resorts, and lush tea plantation retreats.',
    image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1000&q=80',
    hotelCount: 390,
    startingPrice: '₹ 3,800',
    rating: 4.9,
    popular: true,
  },
  {
    id: 'dest-8',
    name: 'Manali',
    state: 'Himachal Pradesh',
    tagline: 'Himalayan Luxury Stays',
    description: 'Snow-capped mountain chalets, cedar forest resorts, and scenic valley hideaways.',
    image: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=1000&q=80',
    hotelCount: 290,
    startingPrice: '₹ 2,299',
    rating: 4.8,
    popular: false,
  }
];
