export const OFFERS = [
  {
    id: 'offer-1',
    title: 'Weekend Getaway Escapes',
    subtitle: 'Flat 30% OFF on Luxury Stays',
    description: 'Book your Friday to Sunday luxury retreat and enjoy complimentary gourmet breakfast + spa access.',
    code: 'WEEKEND30',
    discount: '30% OFF',
    validTill: 'Limited Time Offer',
    gradient: 'from-blue-600 to-indigo-700',
    badge: 'Popular',
    image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'offer-2',
    title: 'Royal Heritage Escapes',
    subtitle: 'Up to ₹ 5,000 Instant Cashback',
    description: 'Experience living like royalty in Rajasthan forts and palace resorts with exclusive privileges.',
    code: 'ROYAL5000',
    discount: '₹ 5,000 OFF',
    validTill: 'Valid till Month End',
    gradient: 'from-amber-500 to-rose-600',
    badge: 'Heritage',
    image: 'https://images.unsplash.com/photo-1590077428593-a55bb07c4665?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'offer-3',
    title: 'Family Vacation Special',
    subtitle: 'Kids Stay & Eat Free',
    description: 'Book 3 nights or more at premier family resorts and get complimentary extra bedding + activity passes.',
    code: 'FAMILYFUN',
    discount: 'Free Meals',
    validTill: 'Summer Special',
    gradient: 'from-teal-500 to-cyan-600',
    badge: 'Family',
    image: 'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'offer-4',
    title: 'Beach Resorts & Ocean Villas',
    subtitle: 'Exclusive Sunset Cocktail Packages',
    description: 'Recharge by the ocean in Goa & Kerala beach resorts with free airport private transfers.',
    code: 'BEACHVIBES',
    discount: '25% OFF',
    validTill: 'Early Bird Deal',
    gradient: 'from-cyan-600 to-blue-700',
    badge: 'Beachfront',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
  }
];
